# Generated by Django 3.0.2 on 2020-02-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
    ]
